# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9008188408754a5d02e57c8d02dfb0d52799bb8f6882a441290d3f87c24601a81c689ca1f985c00bf54b2cf9ee62140b63e85a359fce5cd7c48ff1349971163d

test:
  secret_key_base: ef95bb9b2a1827eb3f2425d1dcca47874664f612b4ba4471f1cd846bd12397cc76b8d550f23ec5d2c08dc48798d8164f2e3925d517fcf7d2e96526ceb7b686f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
